config/routes.rb
Rails.application.routes.draw do
  resources :user_settings
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "home", to:'home#index', as: "home"

  get "inquiries", to: 'inquiries#index', as: "inquiries"

  get "user-settings", to: 'user_settings#index'

  get "user-settings/default", to: 'user_settings#default'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :name,
            :address,
            :sales_rep, presence: true

  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord

  validates :name,
            :email, presence: true

  has_many :inquiries, dependent: :nullify
  has_many :user_settings, dependent: :nullify
end

app/models/user_setting.rb
class UserSetting < ApplicationRecord
  validates :title,
            :key,
            :settings, presence: true

  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
    @inquiries = Inquiry.all

    respond_to do |format|

      format.html # show.html.erb
      format.json { render json: @inquiries }

    end
  end
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  before_action :set_user_setting, only: [:show, :edit, :update, :destroy]

  # GET /user_settings
  # GET /user_settings.json
  def index

      @user_settings = UserSetting.where(key: params[:key], user_id: params[:user_id])

      @user_settings.to_json
  end

  # GET /user_settings/1
  # GET /user_settings/1.json
  def show
  end

  # GET /user_settings/new
  def new
    @user_setting = UserSetting.new
  end

  # GET /user_settings/1/edit
  def edit
  end

  def default
    @user_setting = UserSetting.where(key: params[:key], user_id: params[:user_id], default: true).try(:first)

    return @user_setting.to_json
  end

  # POST /user_settings
  # POST /user_settings.json
  def create
    @user_setting = UserSetting.new(user_setting_params)

    respond_to do |format|
      if @user_setting.save
        format.html { redirect_to @user_setting, notice: 'User setting was successfully created.' }
        format.json { render :show, status: :created, location: @user_setting }
      else
        format.html { render :new }
        format.json { render json: @user_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_settings/1
  # PATCH/PUT /user_settings/1.json
  def update
    respond_to do |format|
      if @user_setting.update(user_setting_params)
        format.html { redirect_to @user_setting, notice: 'User setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_setting }
      else
        format.html { render :edit }
        format.json { render json: @user_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_settings/1
  # DELETE /user_settings/1.json
  def destroy
    @user_setting.destroy
    respond_to do |format|
      format.html { redirect_to user_settings_url, notice: 'User setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_setting
      @user_setting = UserSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_setting_params
      params.require(:user_setting).permit(:title, :key, :user_id, :settings, :default)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="homepage">
</div>

app/views/inquiries/index.html.erb
<div id="inquiries"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>

        <nav id="navigation" class="navbar navbar-default sidebar" role="navigation"></nav>

        <div id="main" class="container-fluid">
          <%= yield %>
        </div>

  </body>
</html>

app/views/user_settings/_form.html.erb
<%= form_with(model: user_setting, local: true) do |form| %>
  <% if user_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_setting.errors.count, "error") %> prohibited this user_setting from being saved:</h2>

      <ul>
      <% user_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key, id: :user_setting_key %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :user_setting_user_id %>
  </div>

  <div class="field">
    <%= form.label :settings %>
    <%= form.text_area :settings, id: :user_setting_settings %>
  </div>

  <div class="field">
    <%= form.label :default %>
    <%= form.check_box :default, id: :user_setting_default %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_settings/edit.html.erb
<h1>Editing User Setting</h1>

<%= render 'form', user_setting: @user_setting %>

<%= link_to 'Show', @user_setting %> |
<%= link_to 'Back', user_settings_path %>

app/views/user_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Settings</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>User</th>
      <th>Settings</th>
      <th>Default</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_settings.each do |user_setting| %>
      <tr>
        <td><%= user_setting.key %></td>
        <td><%= user_setting.user_id %></td>
        <td><%= user_setting.settings %></td>
        <td><%= user_setting.default %></td>
        <td><%= link_to 'Show', user_setting %></td>
        <td><%= link_to 'Edit', edit_user_setting_path(user_setting) %></td>
        <td><%= link_to 'Destroy', user_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Setting', new_user_setting_path %>

app/views/user_settings/new.html.erb
<h1>New User Setting</h1>

<%= render 'form', user_setting: @user_setting %>

<%= link_to 'Back', user_settings_path %>

app/views/user_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @user_setting.key %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_setting.user_id %>
</p>

<p>
  <strong>Settings:</strong>
  <%= @user_setting.settings %>
</p>

<p>
  <strong>Default:</strong>
  <%= @user_setting.default %>
</p>

<%= link_to 'Edit', edit_user_setting_path(@user_setting) %> |
<%= link_to 'Back', user_settings_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>